### ISSUE TITLE
Fabric Crash when creating a world 

### ISSUE THREAD

**Issue by ruguysgoingtrickortreating** [IsaiahMC/multiworld#50]
running /mw create testworld NORMAL crashes the game 
[crash-2023-09-23_16.18.08-server.txt](https://github.com/IsaiahMC/multiworld/files/12707432/crash-2023-09-23_16.18.08-server.txt)

**Comment by ruguysgoingtrickortreating** [comment]
just realized that this from the server log is probably relevant 
```
[16:45:05] [Server thread/INFO]: [STDERR]: java.lang.NullPointerException: invalid dimension type ResourceKey[minecraft:dimension_type / null]
[16:45:05] [Server thread/INFO]: [STDERR]:      at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907)
[16:45:05] [Server thread/INFO]: [STDERR]:      at xyz.nucleoid.fantasy.RuntimeWorldConfig.resolveDimensionType(RuntimeWorldConfig.java:151)
[16:45:05] [Server thread/INFO]: [STDERR]:      at xyz.nucleoid.fantasy.RuntimeWorldConfig.createDimensionOptions(RuntimeWorldConfig.java:143)
[16:45:05] [Server thread/INFO]: [STDERR]:      at xyz.nucleoid.fantasy.RuntimeWorldManager.add(RuntimeWorldManager.java:33)
[16:45:05] [Server thread/INFO]: [STDERR]:      at xyz.nucleoid.fantasy.Fantasy.addPersistentWorld(Fantasy.java:147)
[16:45:05] [Server thread/INFO]: [STDERR]:      at xyz.nucleoid.fantasy.Fantasy.getOrOpenPersistentWorld(Fantasy.java:137)
[16:45:05] [Server thread/INFO]: [STDERR]:      at me.isaiah.multiworld.fabric.FabricWorldCreator.create_world(FabricWorldCreator.java:36)
[16:45:05] [Server thread/INFO]: [STDERR]:      at me.isaiah.multiworld.MultiworldMod.create_world(MultiworldMod.java:60)
[16:45:05] [Server thread/INFO]: [STDERR]:      at me.isaiah.multiworld.command.CreateCommand.run(CreateCommand.java:57)[16:45:05] [Server thread/INFO]: [STDERR]:      at me.isaiah.multiworld.MultiworldMod.broadcast(MultiworldMod.java:204)
[16:45:05] [Server thread/INFO]: [STDERR]:      at me.isaiah.multiworld.MultiworldMod.lambda$register_commands$2(MultiworldMod.java:116)
[16:45:05] [Server thread/INFO]: [STDERR]:      at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[16:45:05] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_2170.method_9249(class_2170.java:287)
[16:45:05] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3244.method_45010(class_3244.java:1341)
[16:45:05] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3244.method_44356(class_3244.java:1321)
[16:45:05] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_1255.method_5386(class_1255.java:67)
[16:45:05] [Server thread/INFO]: [STDERR]:      at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[16:45:05] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3738.run(class_3738.java:18)
[16:45:05] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_1255.method_18859(class_1255.java:156)
[16:45:05] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_4093.method_18859(class_4093.java:23)
[16:45:05] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782)
[16:45:05] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164)
[16:45:05] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_1255.method_16075(class_1255.java:130)
[16:45:05] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764)
[16:45:05] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758)
[16:45:05] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_1255.method_5383(class_1255.java:115)
[16:45:05] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742)
[16:45:05] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
[16:45:05] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
[16:45:05] [Server thread/INFO]: [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by R3tr0PAG** [comment]
I have encountered the same issue, in Singleplayer it works perfectly fine. It's just when trying to create worlds on a server that it freezes and then crashes.

**Comment by ACG94** [comment]
i am also having this issue, but have found when i remove the datapacks from the server, it works fine.... as soon as i add the datapacks back in, it freezes when making a new dimension
