### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.LinkedHashMap.get(Object)" is null

### ISSUE THREAD

**Issue by Healock** [IsaiahMC/multiworld#51]
`
[11:15:55] [Server thread/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return v
alue of "java.util.LinkedHashMap.get(Object)" is null
[11:15:55] [Server thread/INFO]: [STDERR]:      at me.isaiah.multiworld.config.Configuration.getInt(Configuration.java:58)
[11:15:55] [Server thread/INFO]: [STDERR]:      at me.isaiah.multiworld.command.CreateCommand.reinit_world_from_config(CreateCommand.java:93
)
[11:15:55] [Server thread/INFO]: [STDERR]:      at me.isaiah.multiworld.MultiworldMod.on_server_started(MultiworldMod.java:84)
[11:15:55] [Server thread/INFO]: [STDERR]:      at me.isaiah.multiworld.fabric.MultiworldModFabric.lambda$onInitialize$0(MultiworldModFabric
.java:16)
[11:15:55] [Server thread/INFO]: [STDERR]:      at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$2(ServerLi
fecycleEvents.java:49)
[11:15:55] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.handler$cej000$fabric-lifecycle-events-v1$afterSetup
Server(MinecraftServer.java:8342)
[11:15:55] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650)
[11:15:55] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
[11:15:55] [Server thread/INFO]: [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:1583)
`

after that:

`
[11:15:58] [Server thread/INFO]: [STDERR]: com.mojang.brigadier.exceptions.CommandSyntaxException: A player is required to run this command here
[11:15:58] [Server thread/INFO]: [STDERR]: com.mojang.brigadier.exceptions.CommandSyntaxException: A player is required to run this command here
[11:15:58] [Server thread/INFO]: [STDERR]: com.mojang.brigadier.exceptions.CommandSyntaxException: A player is required to run this command here
[11:15:58] [Server thread/INFO]: [STDERR]: com.mojang.brigadier.exceptions.CommandSyntaxException: A player is required to run this command here
[11:15:58] [Server thread/INFO]: [STDERR]: com.mojang.brigadier.exceptions.CommandSyntaxException: A player is required to run this command here
[11:15:58] [Server thread/INFO]: [STDERR]: com.mojang.brigadier.exceptions.CommandSyntaxException: A player is required to run this command here
[11:15:58] [Server thread/INFO]: [STDERR]: com.mojang.brigadier.exceptions.CommandSyntaxException: A player is required to run this command here
[11:15:58] [Server thread/INFO]: [STDERR]: com.mojang.brigadier.exceptions.CommandSyntaxException: A player is required to run this command here
[11:15:58] [Server thread/INFO]: [STDERR]: com.mojang.brigadier.exceptions.CommandSyntaxException: A player is required to run this command here
[11:15:59] [Server thread/INFO]: [STDERR]: com.mojang.brigadier.exceptions.CommandSyntaxException: A player is required to run this command here
[11:15:59] [Server thread/INFO]: [STDERR]: com.mojang.brigadier.exceptions.CommandSyntaxException: A player is required to run this command here
[11:15:59] [Server thread/INFO]: [STDERR]: com.mojang.brigadier.exceptions.CommandSyntaxException: A player is required to run this command here
[11:15:59] [Server thread/INFO]: [STDERR]: com.mojang.brigadier.exceptions.CommandSyntaxException: A player is required to run this command here
`

**Comment by oxzin** [comment]
Still no fix?
