### ISSUE TITLE
1.21 server crash using 1.8.1 (Fabric)

### ISSUE THREAD

**Issue by Saxostevesaxo** [IsaiahMC/multiworld#69]
Crashes the server on startup linked to mixins as far as i can see. I have no other mods installed. thanks

main/ERROR Mixin apply for mod multiworld failed dim.mixins.json:EntityMixin from mod multiworld -> net.minecraft.class_1297: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on getTeleportTarget could not find any targets matching 'Lnet/minecraft/class_1297;method_30329(Lnet/minecraft/class_3218;)Lnet/minecraft/class_5454;' in net.minecraft.class_1297. Using refmap Multiworld-Fabric-Multiworld-Fabric-1.20.6-refmap.json [PREINJECT Applicator Phase -> dim.mixins.json:EntityMixin from mod multiworld -> Prepare Injections ->  -> handler$zin000$multiworld$getTeleportTarget(Lnet/minecraft/class_3218;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
14.06 16:02:25 [Server] INFO org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on getTeleportTarget could not find any targets matching 'Lnet/minecraft/class_1297;method_30329(Lnet/minecraft/class_3218;)Lnet/minecraft/class_5454;' in net.minecraft.class_1297. Using refmap Multiworld-Fabric-Multiworld-Fabric-1.20.6-refmap.json [PREINJECT Applicator Phase -> dim.mixins.json:EntityMixin from mod multiworld -> Prepare Injections ->  -> handler$zin000$multiworld$getTeleportTarget(Lnet/minecraft/class_3218;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
14.06 16:02:25 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:658) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
14.06 16:02:25 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:589) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
14.06 16:02:25 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
14.06 16:02:25 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
14.06 16:02:25 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
14.06 16:02:25 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
14.06 16:02:25 [Server] INFO at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
14.06 16:02:25 [Server] INFO at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
14.06 16:02:25 [Server] INFO at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
14.06 16:02:25 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
14.06 16:02:25 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:710) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
14.06 16:02:25 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1329) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
14.06 16:02:25 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
14.06 16:02:25 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
14.06 16:02:25 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
14.06 16:02:25 [Server] INFO at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
14.06 16:02:25 [Server] INFO at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
14.06 16:02:25 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) [sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
14.06 16:02:25 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
14.06 16:02:25 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
14.06 16:02:25 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) [fabric-loader-0.15.11.jar:?]
14.06 16:02:25 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) [fabric-loader-0.15.11.jar:?]
14.06 16:02:25 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) [fabric-loader-0.15.11.jar:?]
14.06 16:02:25 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) [fabric-loader-0.15.11.jar:?]
14.06 16:02:25 [Server] INFO at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) [?:?]
14.06 16:02:25 [Server] INFO at net.minecraft.class_2966.method_12851(class_2966.java:52) [server-intermediary.jar:?]
14.06 16:02:25 [Server] INFO at net.minecraft.server.Main.main(Main.java:108) [server-intermediary.jar:?]
14.06 16:02:25 [Server] INFO at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
14.06 16:02:25 [Server] INFO at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
14.06 16:02:25 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.15.11.jar:?]
14.06 16:02:25 [Server] INFO at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.15.11.jar:?]
14.06 16:02:25 [Server] INFO at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [Fabric_Latest_1.21.jar:1.0.1]
14.06 16:02:25 [Server] main/ERROR Failed to start the minecraft server
14.06 16:02:25 [Server] INFO java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1297 failed
14.06 16:02:25 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.15.11.jar:?]
14.06 16:02:25 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
14.06 16:02:25 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
14.06 16:02:25 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
14.06 16:02:25 [Server] INFO at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
14.06 16:02:25 [Server] INFO at net.minecraft.class_2966.method_12851(class_2966.java:52) ~[server-intermediary.jar:?]
14.06 16:02:25 [Server] INFO at net.minecraft.server.Main.main(Main.java:108) [server-intermediary.jar:?]
14.06 16:02:25 [Server] INFO at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
14.06 16:02:25 [Server] INFO at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
14.06 16:02:25 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.15.11.jar:?]
14.06 16:02:25 [Server] INFO at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.15.11.jar:?]
14.06 16:02:25 [Server] INFO at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [Fabric_Latest_1.21.jar:1.0.1]
14.06 16:02:25 [Server] INFO Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
14.06 16:02:25 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
14.06 16:02:25 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
14.06 16:02:25 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
14.06 16:02:25 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.11.jar:?]
14.06 16:02:25 [Server] INFO ... 11 more
14.06 16:02:25 [Server] INFO Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [dim.mixins.json:EntityMixin from mod multiworld] from phase [DEFAULT] in config [dim.mixins.json] FAILED during APPLY
14.06 16:02:25 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
14.06 16:02:25 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
14.06 16:02:25 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
14.06 16:02:25 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
14.06 16:02:25 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
14.06 16:02:25 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.11.jar:?]
14.06 16:02:25 [Server] INFO ... 11 more
14.06 16:02:25 [Server] INFO Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on getTeleportTarget could not find any targets matching 'Lnet/minecraft/class_1297;method_30329(Lnet/minecraft/class_3218;)Lnet/minecraft/class_5454;' in net.minecraft.class_1297. Using refmap Multiworld-Fabric-Multiworld-Fabric-1.20.6-refmap.json [PREINJECT Applicator Phase -> dim.mixins.json:EntityMixin from mod multiworld -> Prepare Injections ->  -> handler$zin000$multiworld$getTeleportTarget(Lnet/minecraft/class_3218;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
14.06 16:02:25 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:658) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
14.06 16:02:25 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:589) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
14.06 16:02:25 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
14.06 16:02:25 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
14.06 16:02:25 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
14.06 16:02:25 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
14.06 16:02:25 [Server] INFO at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
14.06 16:02:25 [Server] INFO at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
14.06 16:02:25 [Server] INFO at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
14.06 16:02:25 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
14.06 16:02:25 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:710) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
14.06 16:02:25 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1329) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
14.06 16:02:25 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
14.06 16:02:25 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
14.06 16:02:25 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
14.06 16:02:25 [Server] INFO at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
14.06 16:02:25 [Server] INFO at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
14.06 16:02:25 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
14.06 16:02:25 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
14.06 16:02:25 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
14.06 16:02:25 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.11.jar:?]

**Comment by Rutra09** [comment]
It looks like it's using 1.20.6 minecraft mixins, have u tried using Multiworld-Fabric-Bundle?

**Comment by Saxostevesaxo** [comment]
Hiya, i cant seem to find where i get this file "Multiworld-Fabric-1.21" from?

**Comment by Saxostevesaxo** [comment]
Dont worry, i found it eventually in the output folder, sorry im not too familiar with github. It does work fine with the 1.21 version. you should add this to modrinth. thanks!

**Comment by Saxostevesaxo** [comment]
the 1.21 vesrion from the github fixed the issue, but you should release this to modrinth. Thanks

**Comment by oxzin** [comment]
Hey, can you tell me where is the output folder located at? Also does it work in 1.21.1 too??
