### ISSUE TITLE
Running /mw setspawn in a new world causes the server to crash.

### ISSUE THREAD

**Issue by Karsteski** [IsaiahMC/multiworld#7]
Thanks so much for creating this mod, first of all.

I ran `/mw setspawn` on my second world and my server crashed with the following error message:

```bash
Caused by: java.lang.ClassNotFoundException: net.fabricmc.loader.api.FabricLoaderFeb 07 17:31:09 fedora-server run.sh[82636]:         at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
Feb 07 17:31:09 fedora-server run.sh[82636]:         at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
Feb 07 17:31:09 fedora-server run.sh[82636]:         at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-1.0.1.jar:?]
Feb 07 17:31:09 fedora-server run.sh[82636]:         at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
Feb 07 17:31:09 fedora-server run.sh[82636]:         at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-1.0.1.jar:?]
Feb 07 17:31:09 fedora-server run.sh[82636]:         at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
Feb 07 17:31:09 fedora-server run.sh[82636]:         ... 25 more
Feb 07 17:31:10 fedora-server mcrcon[82895]: Connection failed.
Feb 07 17:31:10 fedora-server mcrcon[82895]: Error 111: Connection refused
```

For more context, I imported a skyblock map and replaced `data/ entities/ region/ of the new world w/ the skyblock map's data. Not sure if that had anything to do with it or not. But given that the mod seems to be calling FabricLoader classes, I'm guessing it's not related. 

Good luck!

**Comment by EndDragon438** [comment]
Experiencing the same issue with a self-hosted forge 1.18.2 server on a custom modpack with a custom world. May be able to provide more info by request.
