### ISSUE TITLE
Support for Minecraft 1.21.1

### ISSUE THREAD

**Issue by timvandenhof** [IsaiahMC/multiworld#75]
Setting up my first Minecraft Fabric server with Multiworld, but I'm currently facing the following error on startup:

```
[TIMESTAMP] [main/WARN]: Mod resolution failed
[TIMESTAMP] [main/INFO]: Immediate reason: [HARD_DEP_INCOMPATIBLE_PRESELECTED multiworld 1.1 {depends minecraft @ [>=1.21- <1.21.1-]}, ROOT_FORCELOAD_SINGLE multiworld 1.1]
[TIMESTAMP] [main/INFO]: Reason: [HARD_DEP multiworld 1.1 {depends minecraft @ [>=1.21- <1.21.1-]}]
[TIMESTAMP] [main/INFO]: SERVER environment disabled: [fabric-renderer-api-v1, fabric-model-loading-api-v1, fabric-keybindings-v0, fabric-renderer-registries-v1, fabric-client-tags-api-v1, fabric-sound-api-v1, fabric-screen-api-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-key-binding-api-v1, fabric-renderer-indigo, fabric-blockrenderlayer-v1]
[TIMESTAMP] [main/INFO]: Fix: add [], remove [], replace [[minecraft 1.21.1] -> add:minecraft 1.21- ([[1.21-,1.21.1-)])]
[TIMESTAMP] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
         - Replace 'Minecraft' (minecraft) 1.21.1 with any version between 1.21- (inclusive) and 1.21.1- (exclusive).
More details:
         - Mod 'Multiworld' (multiworld) 1.1 requires any version between 1.21- (inclusive) and 1.21.1- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
        at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.16.3.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196) ~[fabric-loader-0.16.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.16.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.16.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.3.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.3.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.21.1-loader.0.16.3-launcher.1.0.1.jar:1.0.1]
```

This seems to indicate that Multiworld does not yet support 1.21.1. Are there plans to update to 1.21.1?
Is it known what is needed to go to 1.21.1, not a Java programmer by day but I can at least try to help.

Release notes:
https://www.minecraft.net/en-us/article/minecraft-java-edition-1-21-1

**Comment by timvandenhof** [comment]
Thank you for adding 1.21.1 that quickly. I spotted your commit :-)
https://github.com/IsaiahMC/multiworld/blob/master/output/Multiworld-Fabric-1.21.jar
